export const ONE_SECOND_IN_MS = 1000;

export const ONE_SECOND_IN_SECONDS = 1;
export const ONE_MINUTE_IN_SECONDS = ONE_SECOND_IN_SECONDS * 60;
export const FIFTEEN_MINUTES_IN_SECONDS = ONE_MINUTE_IN_SECONDS * 15;
export const ONE_HOUR_IN_SECONDS = ONE_MINUTE_IN_SECONDS * 60;
export const ONE_DAY_IN_SECONDS = ONE_HOUR_IN_SECONDS * 24;
export const SEVEN_DAYS_IN_SECONDS = ONE_DAY_IN_SECONDS * 7;

export const JWT_FIFTEEN_MINUTES = "15m";
export const JWT_SEVEN_DAYS = "7d";
